# Generated by Django 5.1.7 on 2025-03-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleusuario',
            name='bio',
        ),
    ]
