# Generated by Django 5.1.7 on 2025-03-21 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_notificaciones_amistad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleUsuario',
            new_name='Detalle_usuario',
        ),
        migrations.AlterModelOptions(
            name='notificaciones_amistad',
            options={'verbose_name': 'Notificación de amistad', 'verbose_name_plural': 'Notificaciones de amistad'},
        ),
    ]
