# Generated by Django 5.1.7 on 2025-03-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_detalleusuario_detalle_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_usuario',
            old_name='imagen_perfil_base64',
            new_name='imagen_perfil',
        ),
    ]
