# Generated by Django 5.1.7 on 2025-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0006_rename_imagen_perfil_base64_detalle_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_usuario',
            name='generos',
            field=models.ManyToManyField(related_name='generos_usuario', to='libros.genero'),
        ),
    ]
