# Generated by Django 5.1.7 on 2025-03-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Libro',
                'verbose_name_plural': 'Estados de Libros',
            },
        ),
        migrations.CreateModel(
            name='libro_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentario', models.TextField()),
            ],
            options={
                'verbose_name': 'Libro de Usuario',
                'verbose_name_plural': 'Libros de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='libro_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('comentario', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_grupo', to='libros.estado_libro')),
            ],
            options={
                'verbose_name': 'Libro de Grupo',
                'verbose_name_plural': 'Libros de Grupos',
            },
        ),
    ]
