# Generated by Django 5.1.7 on 2025-03-21 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_estado_libro_libro_usuario_resena_libro_grupo'),
        ('usuarios', '0008_detalle_usuario_libros_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro_grupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='usuarios.grupo'),
        ),
        migrations.AddField(
            model_name='libro_grupo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_grupo', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='libro_usuario',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_usuario', to='libros.estado_libro'),
        ),
        migrations.AddField(
            model_name='libro_usuario',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='libro_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autor',
            name='resena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resena_autor', to='libros.resena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='resena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resena_libro', to='libros.resena'),
            preserve_default=False,
        ),
    ]
